apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kargo-demo
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - stage: test
      - stage: uat
      - stage: prod
  template:
    metadata:
      name: kargo-demo-{{stage}}
      annotations:
        kargo.akuity.io/authorized-stage: kargo-demo:{{stage}}
    spec:
      project: default
      source:
        repoURL: https://github.com/<username>/kargo-demo-gitops.git
        targetRevision: helm
        path: charts/kargo-demo
        helm:
          parameters:
          # Kargo will update this value to move new images into each stage
          - name: image.name
            value: nginx:placeholder
      destination:
        server: https://kubernetes.default.svc
        namespace: kargo-demo-{{stage}}
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
  ignoreApplicationDifferences:
  - jqPathExpressions:
    - .spec.source.helm.parameters
