apiVersion: v1
kind: Namespace
metadata:
  name: kargo-demo
  labels:
    kargo.akuity.io/project: "true"
---
apiVersion: kargo.akuity.io/v1alpha1
kind: PromotionPolicy
metadata:
  name: test
  namespace: kargo-demo
stage: test
enableAutoPromotion: true
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: test
  namespace: kargo-demo
spec:
  subscriptions:
    repos:
      images:
      - repoURL: nginx # Watch for new versions of this image
        semverConstraint: ^1.24.0
  promotionMechanisms:
    argoCDAppUpdates:
    - appName: kargo-demo-test
      appNamespace: argocd
      sourceUpdates:
      - repoURL: https://github.com/<username>/kargo-demo-gitops.git
        helm:
          images:
          - image: nginx
            key: image.name
            value: Image # Update Application to reference the new image version
---
apiVersion: kargo.akuity.io/v1alpha1
kind: PromotionPolicy
metadata:
  name: uat
  namespace: kargo-demo
stage: uat
enableAutoPromotion: true
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: uat
  namespace: kargo-demo
spec:
  subscriptions:
    upstreamStages:
    - name: test # Watch for new versions of the image
  promotionMechanisms:
    argoCDAppUpdates:
    - appName: kargo-demo-uat
      appNamespace: argocd
      sourceUpdates:
      - repoURL: https://github.com/<username>/kargo-demo-gitops.git
        helm:
          images:
          - image: nginx
            key: image.name
            value: Image # Update Application to reference the new image version
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod
  namespace: kargo-demo
spec:
  subscriptions:
    upstreamStages:
    - name: uat # Watch for new versions of the image
  promotionMechanisms:
    argoCDAppUpdates:
    - appName: kargo-demo-prod
      appNamespace: argocd
      sourceUpdates:
      - repoURL: https://github.com/<username>/kargo-demo-gitops.git
        helm:
          images:
          - image: nginx
            key: image.name
            value: Image # Update Application to reference the new image version
