apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: kargo-demo-07
spec:
  promotionPolicies:
  - stage: test
    autoPromotionEnabled: true
  - stage: uat
    autoPromotionEnabled: true
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: image
  namespace: kargo-demo-07
  labels:
    kargo.akuity.io/cred-type: image
stringData:
  repoURL: nginx
  username: <dockerhub-username>
  password: <dockerhub-pat>
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: kargo-demo
  namespace: kargo-demo-07
spec:
  subscriptions:
  - image:
      repoURL: nginx # Watch for new versions of this image
      semverConstraint: ^1.24.0
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: test
  namespace: kargo-demo-07
spec:
  subscriptions:
    warehouse: kargo-demo
  promotionMechanisms:
    argoCDAppUpdates:
    - appName: kargo-demo-07-test
      sourceUpdates:
      - repoURL: https://github.com/<github-username>/kargo-demo-gitops.git
        kustomize:
          images:
          - image: nginx # Update Application to reference the new image version
  verification:
    analysisTemplates:
    - name: kargo-demo
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: uat
  namespace: kargo-demo-07
spec:
  subscriptions:
    upstreamStages:
    - name: test
  promotionMechanisms:
    argoCDAppUpdates:
    - appName: kargo-demo-07-uat
      sourceUpdates:
      - repoURL: https://github.com/<github-username>/kargo-demo-gitops.git
        kustomize:
          images:
          - image: nginx # Update Application to reference the new image version
  verification:
    analysisTemplates:
    - name: kargo-demo
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod
  namespace: kargo-demo-07
spec:
  subscriptions:
    upstreamStages:
    - name: uat
  promotionMechanisms:
    argoCDAppUpdates:
    - appName: kargo-demo-07-prod
      sourceUpdates:
      - repoURL: https://github.com/<github-username>/kargo-demo-gitops.git
        kustomize:
          images:
          - image: nginx # Update Application to reference the new image version
  verification:
    analysisTemplates:
    - name: kargo-demo
---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: kargo-demo
  namespace: kargo-demo-07
spec:
  metrics:
  - name: test
    provider:
      job:
        metadata:
        spec:
          backoffLimit: 1
          template:
            spec:
              containers:
              - name: test
                image: alpine:latest
                command:
                - sleep
                - "20"
              restartPolicy: Never
