apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: kargo-demo-07
spec:
  promotionPolicies:
  - stage: test
    autoPromotionEnabled: true
  - stage: uat
    autoPromotionEnabled: true
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: kargo-demo
  namespace: kargo-demo-07
spec:
  subscriptions:
  - image:
      repoURL: public.ecr.aws/nginx/nginx # Watch for new versions of this image
      semverConstraint: ^1.24.0
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: test
  namespace: kargo-demo-07
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: kargo-demo
    sources:
      direct: true
  promotionMechanisms:
    argoCDAppUpdates:
    - appName: kargo-demo-07-test
      sourceUpdates:
      - repoURL: https://github.com/<github-username>/kargo-demo-gitops.git
        kustomize:
          images:
          - image: public.ecr.aws/nginx/nginx # Update Application to reference the new image version
  verification:
    analysisTemplates:
    - name: kargo-demo
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: uat
  namespace: kargo-demo-07
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: kargo-demo
    sources:
      stages:
      - test
  promotionMechanisms:
    argoCDAppUpdates:
    - appName: kargo-demo-07-uat
      sourceUpdates:
      - repoURL: https://github.com/<github-username>/kargo-demo-gitops.git
        kustomize:
          images:
          - image: public.ecr.aws/nginx/nginx # Update Application to reference the new image version
  verification:
    analysisTemplates:
    - name: kargo-demo
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod
  namespace: kargo-demo-07
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: kargo-demo
    sources:
      stages:
      - uat
  promotionMechanisms:
    argoCDAppUpdates:
    - appName: kargo-demo-07-prod
      sourceUpdates:
      - repoURL: https://github.com/<github-username>/kargo-demo-gitops.git
        kustomize:
          images:
          - image: public.ecr.aws/nginx/nginx # Update Application to reference the new image version
  verification:
    analysisTemplates:
    - name: kargo-demo
---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: kargo-demo
  namespace: kargo-demo-07
spec:
  metrics:
  - name: test
    provider:
      job:
        metadata:
        spec:
          backoffLimit: 1
          template:
            spec:
              containers:
              - name: test
                image: alpine:latest
                command:
                - sleep
                - "20"
              restartPolicy: Never
