apiVersion: v1
kind: Namespace
metadata:
  name: kargo-demo-test
---
apiVersion: v1
kind: Namespace
metadata:
  name: kargo-demo-stage
---
apiVersion: v1
kind: Namespace
metadata:
  name: kargo-demo-prod
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kargo-demo-test
  namespace: argocd
  annotations:
    kargo.akuity.io/authorized-env: kargo-demo:test
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: nginx
    targetRevision: placeholder # We will move new versions of the chart into test by updating this field
    helm:
      parameters:
      - name: image.tag # We will move new versions of the image into test by updating this field
        value: placeholder
      - name: service.type
        value: ClusterIP
  destination:
    server: https://kubernetes.default.svc
    namespace: kargo-demo-test
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kargo-demo-stage
  namespace: argocd
  annotations:
    kargo.akuity.io/authorized-env: kargo-demo:stage
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: nginx
    targetRevision: placeholder # We will move new versions of the chart into stage by updating this field
    helm:
      parameters:
      - name: image.tag
        value: placeholder # We will move new versions of the image into stage by updating this field
      - name: service.type
        value: ClusterIP
  destination:
    server: https://kubernetes.default.svc
    namespace: kargo-demo-stage
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kargo-demo-prod
  namespace: argocd
  annotations:
    kargo.akuity.io/authorized-env: kargo-demo:prod
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: nginx
    targetRevision: placeholder # We will move new versions of the chart into prod by updating this field
    helm:
      parameters:
      - name: image.tag
        value: placeholder # We will move new versions of the image into prod by updating this field
      - name: service.type
        value: ClusterIP
  destination:
    server: https://kubernetes.default.svc
    namespace: kargo-demo-prod
