apiVersion: v1
kind: Namespace
metadata:
  name: kargo-demo
---
apiVersion: kargo.akuity.io/v1alpha1
kind: PromotionPolicy
metadata:
  name: test
  namespace: kargo-demo
environment: test
authorizedPromoters:
- subjectType: Group
  name: system:masters
enableAutoPromotion: true
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Environment
metadata:
  name: test
  namespace: kargo-demo
spec:
  subscriptions:
    repos:
      charts:
      - registryURL: https://charts.bitnami.com/bitnami
        name: nginx # Watch for new versions of this chart
        semverConstraint: ^14.1.0
      images:
      - repoURL: nginx # Watch for new versions of this image
        semverConstraint: ^1.24.0
  promotionMechanisms:
    argoCDAppUpdates:
    - appName: kargo-demo-test
      appNamespace: argocd
      sourceUpdates:
      - repoURL: https://charts.bitnami.com/bitnami
        chart: nginx
        helm:
          images:
          - image: nginx
            key: image.tag
            value: Tag # Update Application to reference the new image version
        updateTargetRevision: true # Update Application to reference the new chart version
---
apiVersion: kargo.akuity.io/v1alpha1
kind: PromotionPolicy
metadata:
  name: stage
  namespace: kargo-demo
environment: stage
authorizedPromoters:
- subjectType: Group
  name: system:masters
enableAutoPromotion: true
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Environment
metadata:
  name: stage
  namespace: kargo-demo
spec:
  subscriptions:
    upstreamEnvs:
    - name: test # Watch for new charts and images
  promotionMechanisms:
    argoCDAppUpdates:
    - appName: kargo-demo-stage
      appNamespace: argocd
      sourceUpdates:
      - repoURL: https://charts.bitnami.com/bitnami
        chart: nginx
        helm:
          images:
          - image: nginx
            key: image.tag
            value: Tag # Update Application to reference the new image version
        updateTargetRevision: true # Update Application to reference the new chart version
---
apiVersion: kargo.akuity.io/v1alpha1
kind: PromotionPolicy
metadata:
  name: prod
  namespace: kargo-demo
environment: prod
authorizedPromoters:
- subjectType: Group
  name: system:masters
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Environment
metadata:
  name: prod
  namespace: kargo-demo
spec:
  subscriptions:
    upstreamEnvs:
    - name: stage # Watch for new charts and images
  promotionMechanisms:
    argoCDAppUpdates:
    - appName: kargo-demo-prod
      appNamespace: argocd
      sourceUpdates:
      - repoURL: https://charts.bitnami.com/bitnami
        chart: nginx
        helm:
          images:
          - image: nginx
            key: image.tag
            value: Tag # Update Application to reference the new image version
        updateTargetRevision: true # Update Application to reference the new chart version
