apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kargo-demo-test
  namespace: argocd
  annotations:
    kargo.akuity.io/authorized-stage: kargo-demo:test
spec:
  project: default
  source:
    repoURL: https://github.com/<username>/kargo-demo-gitops.git
    targetRevision: placeholder # We will move new commits into test by updating this field
    path: stages/test
    kustomize:
      images:
      - nginx=nginx:1.24.0
  destination:
    server: https://kubernetes.default.svc
    namespace: kargo-demo-test
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kargo-demo-uat
  namespace: argocd
  annotations:
    kargo.akuity.io/authorized-stage: kargo-demo:uat
spec:
  project: default
  source:
    repoURL: https://github.com/<username>/kargo-demo-gitops.git
    targetRevision: placeholder # We will move new commits into stage by updating this field
    path: stages/uat
    kustomize:
      images:
      - nginx=nginx:1.24.0
  destination:
    server: https://kubernetes.default.svc
    namespace: kargo-demo-uat
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kargo-demo-prod
  namespace: argocd
  annotations:
    kargo.akuity.io/authorized-stage: kargo-demo:prod
spec:
  project: default
  source:
    repoURL: https://github.com/<username>/kargo-demo-gitops.git
    targetRevision: placeholder # We will move new commits into prod by updating this field
    path: stages/prod
    kustomize:
      images:
      - nginx=nginx:1.24.0
  destination:
    server: https://kubernetes.default.svc
    namespace: kargo-demo-prod
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
