apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: kargo-demo-15
spec:
  promotionPolicies:
  - stage: test
    autoPromotionEnabled: true
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: kargo-demo
  namespace: kargo-demo-15
spec:
  subscriptions:
  - image:
      repoURL: public.ecr.aws/nginx/nginx
      semverConstraint: ^1.24.0
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: slack
  namespace: kargo-demo-15
stringData:
  token: foo
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: test
  namespace: kargo-demo-15
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: kargo-demo
    sources:
      direct: true
  promotionTemplate:
    spec:
      vars:
      - name: repoURL
        value: public.ecr.aws/nginx/nginx
      - name: url
        value: http://192.168.2.117:8080
      - name: slackChannel
        value: C123456
      steps:
      - uses: http
        config:
          method: POST
          url: ${{ vars.url }}
          headers:
          - name: Content-Type
            value: application/json
          - name: Authorization
            value: Bearer ${{ secrets.slack.token }}
          body: |
            ${{ quote({
              "channel": vars.slackChannel,
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Updated " + ctx.stage + " to use image " + vars.repoURL + ":" + imageFrom(vars.repoURL).Tag
                  }
                }
              ]
            }) }}
