apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: kargo-demo-15
spec:
  promotionPolicies:
  - stage: test
    autoPromotionEnabled: true
  - stage: uat
    autoPromotionEnabled: true
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: kargo-demo
  namespace: kargo-demo-15
  labels:
    kargo.akuity.io/cred-type: git
stringData:
  repoURL: https://github.com/<username>/kargo-demo-gitops.git
  username: <username>
  password: <PAT>
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: kargo-demo
  namespace: kargo-demo-15
spec:
  subscriptions:
  - git:
      repoURL: https://github.com/<username>/kargo-demo-gitops.git
      # Watch this branch instead of main. This is the "trunk" for this example.
      branch: kargo-render
  - image:
      repoURL: nginx
      semverConstraint: ^1.24.0
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: test
  namespace: kargo-demo-15
spec:
  subscriptions:
    warehouse: kargo-demo
  promotionMechanisms:
    gitRepoUpdates:
    - repoURL: https://github.com/<username>/kargo-demo-gitops.git
      writeBranch: 15/stage/test # Write to stage-specific branch
      render: {}
    argoCDAppUpdates:
    - appName: kargo-demo-15-test
  verification:
    analysisTemplates:
    - name: kargo-demo
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: uat
  namespace: kargo-demo-15
spec:
  subscriptions:
    upstreamStages:
    - name: test
  promotionMechanisms:
    gitRepoUpdates:
    - repoURL: https://github.com/<username>/kargo-demo-gitops.git
      writeBranch: 15/stage/uat # Write to stage-specific branch
      render: {}
    argoCDAppUpdates:
    - appName: kargo-demo-15-uat
  verification:
    analysisTemplates:
    - name: kargo-demo
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod
  namespace: kargo-demo-15
spec:
  subscriptions:
    upstreamStages:
    - name: uat
  promotionMechanisms:
    gitRepoUpdates:
    - repoURL: https://github.com/<username>/kargo-demo-gitops.git
      writeBranch: 15/stage/prod # Write to stage-specific branch
      render: {}
    argoCDAppUpdates:
    - appName: kargo-demo-15-prod
  verification:
    analysisTemplates:
    - name: kargo-demo
---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: kargo-demo
  namespace: kargo-demo-15
spec:
  metrics:
  - name: test
    provider:
      job:
        metadata:
        spec:
          backoffLimit: 1
          template:
            spec:
              containers:
              - name: test
                image: alpine:latest
                command:
                - sleep
                - "20"
              restartPolicy: Never
