apiVersion: v1
kind: Namespace
metadata:
  name: kargo-demo-test
---
apiVersion: v1
kind: Namespace
metadata:
  name: kargo-demo-stage
---
apiVersion: v1
kind: Namespace
metadata:
  name: kargo-demo-prod
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: kargo-demo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
  annotations:
    kargo.akuity.io/authorized-projects: kargo-demo
stringData:
  type: git
  url: https://github.com/<username>/kargo-demo-gitops.git
  username: <username>
  password: <PAT>
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kargo-demo-test
  namespace: argocd
  annotations:
    kargo.akuity.io/authorized-env: kargo-demo:test
spec:
  project: default
  source:
    repoURL: https://github.com/<username>/kargo-demo-gitops.git
    targetRevision: env/test # We will move new versions of the image AND new commits into test by updating this branch
    path: env/test
  destination:
    server: https://kubernetes.default.svc
    namespace: kargo-demo-test
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kargo-demo-stage
  namespace: argocd
  annotations:
    kargo.akuity.io/authorized-env: kargo-demo:stage
spec:
  project: default
  source:
    repoURL: https://github.com/<username>/kargo-demo-gitops.git
    targetRevision: env/stage # We will move new versions of the image AND new commits into stage by updating this branch
    path: env/stage
  destination:
    server: https://kubernetes.default.svc
    namespace: kargo-demo-stage
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kargo-demo-prod
  namespace: argocd
  annotations:
    kargo.akuity.io/authorized-env: kargo-demo:prod
spec:
  project: default
  source:
    repoURL: https://github.com/<username>/kargo-demo-gitops.git
    targetRevision: env/prod # We will move new versions of the image AND new commits into prod by updating this branch
    path: env/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: kargo-demo-prod
