apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: kargo-demo
spec:
  promotionPolicies:
  - stage: test
    autoPromotionEnabled: true
  - stage: uat
    autoPromotionEnabled: true
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: kargo-demo
  namespace: kargo-demo
spec:
  subscriptions:
  - chart:
      registryURL: https://charts.bitnami.com/bitnami
      name: nginx # Watch for new versions of this chart
      semverConstraint: ^14.1.0
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: test
  namespace: kargo-demo
spec:
  subscriptions:
    warehouse: kargo-demo
  promotionMechanisms:
    argoCDAppUpdates:
    - appName: kargo-demo-test
      sourceUpdates:
      - repoURL: https://charts.bitnami.com/bitnami
        chart: nginx
        updateTargetRevision: true # Update Application to reference the new chart version
  verification:
    analysisTemplates:
    - name: kargo-demo
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: uat
  namespace: kargo-demo
spec:
  subscriptions:
    upstreamStages:
    - name: test # Watch for new versions of the chart
  promotionMechanisms:
    argoCDAppUpdates:
    - appName: kargo-demo-uat
      sourceUpdates:
      - repoURL: https://charts.bitnami.com/bitnami
        chart: nginx
        updateTargetRevision: true # Update Application to reference the new chart version
  verification:
    analysisTemplates:
    - name: kargo-demo
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod
  namespace: kargo-demo
spec:
  subscriptions:
    upstreamStages:
    - name: uat # Watch for new versions of the chart
  promotionMechanisms:
    argoCDAppUpdates:
    - appName: kargo-demo-prod
      sourceUpdates:
      - repoURL: https://charts.bitnami.com/bitnami
        chart: nginx
        updateTargetRevision: true # Update Application to reference the new chart version
  verification:
    analysisTemplates:
    - name: kargo-demo
---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: kargo-demo
  namespace: kargo-demo
spec:
  metrics:
  - name: test
    provider:
      job:
        metadata:
        spec:
          backoffLimit: 1
          template:
            spec:
              containers:
              - name: test
                image: alpine:latest
                command:
                - sleep
                - "20"
              restartPolicy: Never
