apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: kargo-demo-02
spec:
  promotionPolicies:
  - stage: test
    autoPromotionEnabled: true
  - stage: uat
    autoPromotionEnabled: true
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: kargo-demo
  namespace: kargo-demo-02
spec:
  subscriptions:
  - chart:
      repoURL: https://charts.bitnami.com/bitnami
      name: nginx # Watch for new versions of this chart
      semverConstraint: ^14.1.0
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: test
  namespace: kargo-demo-02
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: kargo-demo
    sources:
      direct: true
  promotionMechanisms:
    argoCDAppUpdates:
    - appName: kargo-demo-02-test
      sourceUpdates:
      - repoURL: https://charts.bitnami.com/bitnami
        chart: nginx
        updateTargetRevision: true # Update Application to reference the new chart version
  verification:
    analysisTemplates:
    - name: kargo-demo
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: uat
  namespace: kargo-demo-02
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: kargo-demo
    sources:
      stages:
      - test
  promotionMechanisms:
    argoCDAppUpdates:
    - appName: kargo-demo-02-uat
      sourceUpdates:
      - repoURL: https://charts.bitnami.com/bitnami
        chart: nginx
        updateTargetRevision: true # Update Application to reference the new chart version
  verification:
    analysisTemplates:
    - name: kargo-demo
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod
  namespace: kargo-demo-02
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: kargo-demo
    sources:
      stages:
      - uat
  promotionMechanisms:
    argoCDAppUpdates:
    - appName: kargo-demo-02-prod
      sourceUpdates:
      - repoURL: https://charts.bitnami.com/bitnami
        chart: nginx
        updateTargetRevision: true # Update Application to reference the new chart version
  verification:
    analysisTemplates:
    - name: kargo-demo
---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: kargo-demo
  namespace: kargo-demo-02
spec:
  metrics:
  - name: test
    provider:
      job:
        metadata:
        spec:
          backoffLimit: 1
          template:
            spec:
              containers:
              - name: test
                image: alpine:latest
                command:
                - sleep
                - "20"
              restartPolicy: Never
