apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kargo-demo-09
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - stage: test
      - stage: uat
      - stage: prod
  template:
    metadata:
      name: kargo-demo-09-{{stage}}
      annotations:
        kargo.akuity.io/authorized-stage: kargo-demo-09:{{stage}}
    spec:
      project: default
      source:
        repoURL: https://github.com/<username>/kargo-demo-gitops.git
        # Kargo will update this branch to move new commits from the commit-only
        # branch into this stage
        targetRevision: 09/stage/{{stage}}
        path: stages/{{stage}}
        kustomize:
          images:
          - nginx=nginx:1.24.0
      destination:
        server: https://kubernetes.default.svc
        namespace: kargo-demo-09-{{stage}}
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
