apiVersion: v1
kind: Namespace
metadata:
  name: kargo-demo
  labels:
    kargo.akuity.io/project: "true"
---
apiVersion: kargo.akuity.io/v1alpha1
kind: PromotionPolicy
metadata:
  name: test
  namespace: kargo-demo
stage: test
enableAutoPromotion: true
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: test
  namespace: kargo-demo
spec:
  subscriptions:
    repos:
      images:
      - repoURL: nginx
        semverConstraint: ^1.24.0
  promotionMechanisms:
    gitRepoUpdates:
    - repoURL: https://github.com/krancour/kargo-demo-gitops-2.git
      readBranch: control-flow-experiment
      writeBranch: stage/test
      bookkeeper: {}
    argoCDAppUpdates:
    - appName: kargo-demo-test
---
apiVersion: kargo.akuity.io/v1alpha1
kind: PromotionPolicy
metadata:
  name: uat-1
  namespace: kargo-demo
stage: uat-1
enableAutoPromotion: true
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: uat-1
  namespace: kargo-demo
spec:
  subscriptions:
    upstreamStages:
    - name: test
  promotionMechanisms:
    gitRepoUpdates:
    - repoURL: https://github.com/krancour/kargo-demo-gitops-2.git
      readBranch: control-flow-experiment
      writeBranch: stage/uat-1
      bookkeeper: {}
    argoCDAppUpdates:
    - appName: kargo-demo-uat-1
---
apiVersion: kargo.akuity.io/v1alpha1
kind: PromotionPolicy
metadata:
  name: uat-2
  namespace: kargo-demo
stage: uat-2
enableAutoPromotion: true
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: uat-2
  namespace: kargo-demo
spec:
  subscriptions:
    upstreamStages:
    - name: test
  promotionMechanisms:
    gitRepoUpdates:
    - repoURL: https://github.com/krancour/kargo-demo-gitops-2.git
      readBranch: control-flow-experiment
      writeBranch: stage/uat-2
      bookkeeper: {}
    argoCDAppUpdates:
    - appName: kargo-demo-uat-2
---
apiVersion: kargo.akuity.io/v1alpha1
kind: PromotionPolicy
metadata:
  name: uat-3
  namespace: kargo-demo
stage: uat-3
enableAutoPromotion: true
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: uat-3
  namespace: kargo-demo
spec:
  subscriptions:
    upstreamStages:
    - name: test
  promotionMechanisms:
    gitRepoUpdates:
    - repoURL: https://github.com/krancour/kargo-demo-gitops-2.git
      readBranch: control-flow-experiment
      writeBranch: stage/uat-3
      bookkeeper: {}
    argoCDAppUpdates:
    - appName: kargo-demo-uat-3
---
apiVersion: kargo.akuity.io/v1alpha1
kind: PromotionPolicy
metadata:
  name: ready-for-prod
  namespace: kargo-demo
stage: ready-for-prod
enableAutoPromotion: true
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: ready-for-prod
  namespace: kargo-demo
spec:
  subscriptions:
    upstreamStages:
    - name: uat-1
    - name: uat-2
    - name: uat-3
---
apiVersion: kargo.akuity.io/v1alpha1
kind: PromotionPolicy
metadata:
  name: prod-1
  namespace: kargo-demo
stage: prod-1
enableAutoPromotion: true
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod-1
  namespace: kargo-demo
spec:
  subscriptions:
    upstreamStages:
    - name: ready-for-prod
  promotionMechanisms:
    gitRepoUpdates:
    - repoURL: https://github.com/krancour/kargo-demo-gitops-2.git
      readBranch: control-flow-experiment
      writeBranch: stage/prod-1
      bookkeeper: {}
    argoCDAppUpdates:
    - appName: kargo-demo-prod-1
---
apiVersion: kargo.akuity.io/v1alpha1
kind: PromotionPolicy
metadata:
  name: prod-2
  namespace: kargo-demo
stage: prod-2
enableAutoPromotion: true
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod-2
  namespace: kargo-demo
spec:
  subscriptions:
    upstreamStages:
    - name: ready-for-prod
  promotionMechanisms:
    gitRepoUpdates:
    - repoURL: https://github.com/krancour/kargo-demo-gitops-2.git
      readBranch: control-flow-experiment
      writeBranch: stage/prod-2
      bookkeeper: {}
    argoCDAppUpdates:
    - appName: kargo-demo-prod-2
---
apiVersion: kargo.akuity.io/v1alpha1
kind: PromotionPolicy
metadata:
  name: prod-3
  namespace: kargo-demo
stage: prod-3
enableAutoPromotion: true
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod-3
  namespace: kargo-demo
spec:
  subscriptions:
    upstreamStages:
    - name: ready-for-prod
  promotionMechanisms:
    gitRepoUpdates:
    - repoURL: https://github.com/krancour/kargo-demo-gitops-2.git
      readBranch: control-flow-experiment
      writeBranch: stage/prod-3
      bookkeeper: {}
    argoCDAppUpdates:
    - appName: kargo-demo-prod-3
