apiVersion: v1
kind: Namespace
metadata:
  name: kargo-demo
---
apiVersion: kargo.akuity.io/v1alpha1
kind: PromotionPolicy
metadata:
  name: test
  namespace: kargo-demo
environment: test
authorizedPromoters:
- subjectType: Group
  name: system:masters
enableAutoPromotion: true
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Environment
metadata:
  name: test
  namespace: kargo-demo
spec:
  subscriptions:
    repos:
      git:
      - repoURL: https://github.com/<username>/kargo-demo-gitops.git
        branch: helm # Watch this branch for new commits
      images:
      - repoURL: nginx # Watch for new versions of this image
        semverConstraint: ^1.24.0
  promotionMechanisms:
    gitRepoUpdates:
    - repoURL: https://github.com/<username>/kargo-demo-gitops.git
      writeBranch: env/test # Writing to env-specific branch prevents the formation of a loop
      helm:
        images:
        - image: nginx
          valuesFilePath: charts/kargo-demo/env/test/values.yaml
          key: image.name # Update this key to reference the new image version
          value: Image
    argoCDAppUpdates:
    - appName: kargo-demo-test
      appNamespace: argocd
  healthChecks:
    argoCDAppChecks:
    - appName: kargo-demo-test
      appNamespace: argocd
---
apiVersion: kargo.akuity.io/v1alpha1
kind: PromotionPolicy
metadata:
  name: stage
  namespace: kargo-demo
environment: stage
authorizedPromoters:
- subjectType: Group
  name: system:masters
enableAutoPromotion: true
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Environment
metadata:
  name: stage
  namespace: kargo-demo
spec:
  subscriptions:
    upstreamEnvs:
    - name: test # Watch for new commits and images
  promotionMechanisms:
    gitRepoUpdates:
    - repoURL: https://github.com/<username>/kargo-demo-gitops.git
      writeBranch: env/stage # Writing to env-specific branch prevents the formation of a loop
      helm:
        images:
        - image: nginx
          valuesFilePath: charts/kargo-demo/env/stage/values.yaml
          key: image.name # Update this key to reference the new image version
          value: Image
    argoCDAppUpdates:
    - appName: kargo-demo-stage
      appNamespace: argocd
  healthChecks:
    argoCDAppChecks:
    - appName: kargo-demo-stage
      appNamespace: argocd
---
apiVersion: kargo.akuity.io/v1alpha1
kind: PromotionPolicy
metadata:
  name: prod
  namespace: kargo-demo
environment: prod
authorizedPromoters:
- subjectType: Group
  name: system:masters
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Environment
metadata:
  name: prod
  namespace: kargo-demo
spec:
  subscriptions:
    upstreamEnvs:
    - name: stage # Watch for new commits and images
  promotionMechanisms:
    gitRepoUpdates:
    - repoURL: https://github.com/<username>/kargo-demo-gitops.git
      writeBranch: env/prod # Writing to env-specific branch prevents the formation of a loop
      helm:
        images:
        - image: nginx
          valuesFilePath: charts/kargo-demo/env/prod/values.yaml
          key: image.name # Update this key to reference the new image version
          value: Image
    argoCDAppUpdates:
    - appName: kargo-demo-prod
      appNamespace: argocd
  healthChecks:
    argoCDAppChecks:
    - appName: kargo-demo-prod
      appNamespace: argocd
