apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: kargo-demo-10
spec:
  promotionPolicies:
  - stage: test
    autoPromotionEnabled: true
  - stage: uat
    autoPromotionEnabled: true
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: manifests
  namespace: kargo-demo-10
  labels:
    kargo.akuity.io/cred-type: git
stringData:
  repoURL: https://github.com/<github-username>/kargo-demo-gitops.git
  username: <github-username>
  password: <github-pat>
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: kargo-demo
  namespace: kargo-demo-10
spec:
  subscriptions:
  - image:
      repoURL: public.ecr.aws/nginx/nginx # Watch for new versions of this image
      semverConstraint: ^1.24.0
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: test
  namespace: kargo-demo-10
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: kargo-demo
    sources:
      direct: true
  promotionMechanisms:
    gitRepoUpdates:
    - repoURL: https://github.com/<github-username>/kargo-demo-gitops.git
      readBranch: helm
      writeBranch: 10/stage/test # Write to stage-specific branch
      helm:
        images:
        - image: public.ecr.aws/nginx/nginx
          valuesFilePath: charts/kargo-demo/stages/test/values.yaml
          key: image.name # Update this key to reference the new image version
          value: ImageAndTag
    argoCDAppUpdates:
    - appName: kargo-demo-10-test
  verification:
    analysisTemplates:
    - name: kargo-demo
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: uat
  namespace: kargo-demo-10
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: kargo-demo
    sources:
      stages:
      - test
  promotionMechanisms:
    gitRepoUpdates:
    - repoURL: https://github.com/<github-username>/kargo-demo-gitops.git
      readBranch: helm
      writeBranch: 10/stage/uat # Write to stage-specific branch
      helm:
        images:
        - image: public.ecr.aws/nginx/nginx
          valuesFilePath: charts/kargo-demo/stages/uat/values.yaml
          key: image.name # Update this key to reference the new image version
          value: ImageAndTag
    argoCDAppUpdates:
    - appName: kargo-demo-10-uat
  verification:
    analysisTemplates:
    - name: kargo-demo
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod
  namespace: kargo-demo-10
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: kargo-demo
    sources:
      stages:
      - uat
  promotionMechanisms:
    gitRepoUpdates:
    - repoURL: https://github.com/<github-username>/kargo-demo-gitops.git
      readBranch: helm
      writeBranch: 10/stage/prod # Write to stage-specific branch
      helm:
        images:
        - image: public.ecr.aws/nginx/nginx
          valuesFilePath: charts/kargo-demo/stages/prod/values.yaml
          key: image.name # Update this key to reference the new image version
          value: ImageAndTag
    argoCDAppUpdates:
    - appName: kargo-demo-10-prod
  verification:
    analysisTemplates:
    - name: kargo-demo
---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: kargo-demo
  namespace: kargo-demo-10
spec:
  metrics:
  - name: test
    provider:
      job:
        metadata:
        spec:
          backoffLimit: 1
          template:
            spec:
              containers:
              - name: test
                image: alpine:latest
                command:
                - sleep
                - "20"
              restartPolicy: Never
