apiVersion: v1
kind: Namespace
metadata:
  name: kargo-demo
  labels:
    kargo.akuity.io/project: "true"
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: kargo-demo
  namespace: kargo-demo
  labels:
    kargo.akuity.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/<username>/kargo-demo-gitops.git
  username: <username>
  password: <PAT>
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: kargo-demo
  namespace: kargo-demo
spec:
  subscriptions:
  - image:
      repoURL: nginx # Watch for new versions of this image
      semverConstraint: ^1.24.0
---
apiVersion: kargo.akuity.io/v1alpha1
kind: PromotionPolicy
metadata:
  name: test
  namespace: kargo-demo
stage: test
enableAutoPromotion: true
---
apiVersion: kargo.akuity.io/v1alpha1
kind: PromotionPolicy
metadata:
  name: uat
  namespace: kargo-demo
stage: uat
enableAutoPromotion: true
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: test
  namespace: kargo-demo
spec:
  subscriptions:
    warehouse: kargo-demo
  promotionMechanisms:
    gitRepoUpdates:
    - repoURL: https://github.com/<username>/kargo-demo-gitops.git
      readBranch: helm
      writeBranch: stage/test # Write to stage-specific branch
      helm:
        images:
        - image: nginx
          valuesFilePath: charts/kargo-demo/stages/test/values.yaml
          key: image.name # Update this key to reference the new image version
          value: Image
    argoCDAppUpdates:
    - appName: kargo-demo-test
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: uat
  namespace: kargo-demo
spec:
  subscriptions:
    upstreamStages:
    - name: test # Watch for new versions of the image
  promotionMechanisms:
    gitRepoUpdates:
    - repoURL: https://github.com/<username>/kargo-demo-gitops.git
      readBranch: helm
      writeBranch: stage/uat # Write to stage-specific branch
      helm:
        images:
        - image: nginx
          valuesFilePath: charts/kargo-demo/stages/uat/values.yaml
          key: image.name # Update this key to reference the new image version
          value: Image
    argoCDAppUpdates:
    - appName: kargo-demo-uat
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod
  namespace: kargo-demo
spec:
  subscriptions:
    upstreamStages:
    - name: uat # Watch for new versions of the image
  promotionMechanisms:
    gitRepoUpdates:
    - repoURL: https://github.com/<username>/kargo-demo-gitops.git
      readBranch: helm
      writeBranch: stage/prod # Write to stage-specific branch
      helm:
        images:
        - image: nginx
          valuesFilePath: charts/kargo-demo/stages/prod/values.yaml
          key: image.name # Update this key to reference the new image version
          value: Image
    argoCDAppUpdates:
    - appName: kargo-demo-prod
