apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: kargo-demo-10
spec:
  promotionPolicies:
  - stage: test
    autoPromotionEnabled: true
  - stage: uat
    autoPromotionEnabled: true
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: manifests
  namespace: kargo-demo-10
  labels:
    kargo.akuity.io/cred-type: git
stringData:
  repoURL: https://github.com/<github-username>/kargo-demo-gitops.git
  username: <github-username>
  password: <github-pat>
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: kargo-demo
  namespace: kargo-demo-10
spec:
  subscriptions:
  - image:
      repoURL: public.ecr.aws/nginx/nginx # Watch for new versions of this image
      semverConstraint: ^1.24.0
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: test
  namespace: kargo-demo-10
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: kargo-demo
    sources:
      direct: true
  promotionTemplate:
    spec:
      steps:
      - uses: git-clone
        config:
          repoURL: https://github.com/<github-username>/kargo-demo-gitops.git
          checkout:
          - branch: new-helm
            path: ./src
          - branch: 10/stage/test
            create: true
            path: ./out
      - uses: git-clear
        config:
          path: ./out
      - uses: helm-update-image
        as: update-image
        config:
          path: ./src/charts/kargo-demo/values.yaml
          images:
          - image: public.ecr.aws/nginx/nginx
            key: image.name
            value: ImageAndTag
      - uses: helm-template
        config:
          path: ./src/charts/kargo-demo
          releaseName: kargo-demo
          valuesFiles:
          - ./src/charts/kargo-demo/stages/test/values.yaml
          outPath: ./out
      - uses: git-commit
        as: commit
        config:
          path: ./out
          messageFromSteps:
          - update-image
      - uses: git-push
        config:
          path: ./out
          targetBranch: 10/stage/test
      - uses: argocd-update
        config:
          apps:
          - name: kargo-demo-10-test
            sources:
            - repoURL: https://github.com/<github-username>/kargo-demo-gitops.git
              desiredCommitFromStep: commit
  verification:
    analysisTemplates:
    - name: kargo-demo
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: uat
  namespace: kargo-demo-10
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: kargo-demo
    sources:
      stages:
      - test
  promotionTemplate:
    spec:
      steps:
      - uses: git-clone
        config:
          repoURL: https://github.com/<github-username>/kargo-demo-gitops.git
          checkout:
          - branch: new-helm
            path: ./src
          - branch: 10/stage/uat
            create: true
            path: ./out
      - uses: git-clear
        config:
          path: ./out
      - uses: helm-update-image
        as: update-image
        config:
          path: ./src/charts/kargo-demo/values.yaml
          images:
          - image: public.ecr.aws/nginx/nginx
            key: image.name
            value: ImageAndTag
      - uses: helm-template
        config:
          path: ./src/charts/kargo-demo
          releaseName: kargo-demo
          valuesFiles:
          - ./src/charts/kargo-demo/stages/uat/values.yaml
          outPath: ./out
      - uses: git-commit
        as: commit
        config:
          path: ./out
          messageFromSteps:
          - update-image
      - uses: git-push
        config:
          path: ./out
          targetBranch: 10/stage/uat
      - uses: argocd-update
        config:
          apps:
          - name: kargo-demo-10-uat
            sources:
            - repoURL: https://github.com/<github-username>/kargo-demo-gitops.git
              desiredCommitFromStep: commit
  verification:
    analysisTemplates:
    - name: kargo-demo
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod
  namespace: kargo-demo-10
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: kargo-demo
    sources:
      stages:
      - uat
  promotionTemplate:
    spec:
      steps:
      - uses: git-clone
        config:
          repoURL: https://github.com/<github-username>/kargo-demo-gitops.git
          checkout:
          - branch: new-helm
            path: ./src
          - branch: 10/stage/prod
            create: true
            path: ./out
      - uses: git-clear
        config:
          path: ./out
      - uses: helm-update-image
        as: update-image
        config:
          path: ./src/charts/kargo-demo/values.yaml
          images:
          - image: public.ecr.aws/nginx/nginx
            key: image.name
            value: ImageAndTag
      - uses: helm-template
        config:
          path: ./src/charts/kargo-demo
          releaseName: kargo-demo
          valuesFiles:
          - ./src/charts/kargo-demo/stages/prod/values.yaml
          outPath: ./out
      - uses: git-commit
        as: commit
        config:
          path: ./out
          messageFromSteps:
          - update-image
      - uses: git-push
        as: push
        config:
          path: ./out
          generateTargetBranch: true
      - uses: git-open-pr
        as: open-pr
        config:
          repoURL: https://github.com/<github-username>/kargo-demo-gitops.git
          createTargetBranch: true
          sourceBranchFromStep: push
          targetBranch: 10/stage/prod
      - uses: git-wait-for-pr
        as: wait-for-pr
        config:
          repoURL: https://github.com/<github-username>/kargo-demo-gitops.git
          prNumberFromStep: open-pr
      - uses: argocd-update
        config:
          apps:
          - name: kargo-demo-10-prod
            sources:
            - repoURL: https://github.com/<github-username>/kargo-demo-gitops.git
              desiredCommitFromStep: wait-for-pr
  verification:
    analysisTemplates:
    - name: kargo-demo
---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: kargo-demo
  namespace: kargo-demo-10
spec:
  metrics:
  - name: test
    provider:
      job:
        metadata:
        spec:
          backoffLimit: 1
          template:
            spec:
              containers:
              - name: test
                image: alpine:latest
                command:
                - sleep
                - "20"
              restartPolicy: Never
