apiVersion: v1
kind: Namespace
metadata:
  name: kargo-demo
  labels:
    kargo.akuity.io/project: "true"
---
apiVersion: kargo.akuity.io/v1alpha1
kind: PromotionPolicy
metadata:
  name: test
  namespace: kargo-demo
stage: test
enableAutoPromotion: true
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: test
  namespace: kargo-demo
spec:
  subscriptions:
    repos:
      images:
      - repoURL: nginx
        semverConstraint: ^1.24.0
  promotionMechanisms:
    gitRepoUpdates:
    - repoURL: https://github.com/<username>/kargo-demo-gitops.git
      readBranch: bookkeeper
      writeBranch: stage/test
      bookkeeper: {}
    argoCDAppUpdates:
    - appName: kargo-demo-test
---
apiVersion: kargo.akuity.io/v1alpha1
kind: PromotionPolicy
metadata:
  name: uat
  namespace: kargo-demo
stage: uat
enableAutoPromotion: true
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: uat
  namespace: kargo-demo
spec:
  subscriptions:
    upstreamStages:
    - name: test
  promotionMechanisms:
    gitRepoUpdates:
    - repoURL: https://github.com/<username>/kargo-demo-gitops.git
      readBranch: bookkeeper
      writeBranch: stage/uat
      bookkeeper: {}
    argoCDAppUpdates:
    - appName: kargo-demo-uat
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod
  namespace: kargo-demo
spec:
  subscriptions:
    upstreamStages:
    - name: uat
  promotionMechanisms:
    gitRepoUpdates:
    - repoURL: https://github.com/<username>/kargo-demo-gitops.git
      readBranch: bookkeeper
      writeBranch: stage/prod
      bookkeeper: {}
    argoCDAppUpdates:
    - appName: kargo-demo-prod
