apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: kargo-demo-03
spec:
  promotionPolicies:
  - stage: test
    autoPromotionEnabled: true
  - stage: uat
    autoPromotionEnabled: true
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: kargo-demo
  namespace: kargo-demo-03
spec:
  subscriptions:
  - image:
      repoURL: public.ecr.aws/nginx/nginx # Watch for new versions of this image
      semverConstraint: ^1.24.0
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: test
  namespace: kargo-demo-03
spec:
  subscriptions:
    warehouse: kargo-demo
  promotionMechanisms:
    argoCDAppUpdates:
    - appName: kargo-demo-03-test
      sourceUpdates:
      - repoURL: https://charts.bitnami.com/bitnami
        chart: nginx
        helm:
          images:
          - image: public.ecr.aws/nginx/nginx
            key: image.tag
            value: Tag # Update Application to reference the new image version
  verification:
    analysisTemplates:
    - name: kargo-demo
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: uat
  namespace: kargo-demo-03
spec:
  subscriptions:
    upstreamStages:
    - name: test # Watch for new versions of the image
  promotionMechanisms:
    argoCDAppUpdates:
    - appName: kargo-demo-03-uat
      sourceUpdates:
      - repoURL: https://charts.bitnami.com/bitnami
        chart: nginx
        helm:
          images:
          - image: public.ecr.aws/nginx/nginx
            key: image.tag
            value: Tag # Update Application to reference the new image version
  verification:
    analysisTemplates:
    - name: kargo-demo
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod
  namespace: kargo-demo-03
spec:
  subscriptions:
    upstreamStages:
    - name: uat # Watch for new versions of the image
  promotionMechanisms:
    argoCDAppUpdates:
    - appName: kargo-demo-03-prod
      sourceUpdates:
      - repoURL: https://charts.bitnami.com/bitnami
        chart: nginx
        helm:
          images:
          - image: public.ecr.aws/nginx/nginx
            key: image.tag
            value: Tag # Update Application to reference the new image version
  verification:
    analysisTemplates:
    - name: kargo-demo
---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: kargo-demo
  namespace: kargo-demo-03
spec:
  metrics:
  - name: test
    provider:
      job:
        metadata:
        spec:
          backoffLimit: 1
          template:
            spec:
              containers:
              - name: test
                image: alpine:latest
                command:
                - sleep
                - "20"
              restartPolicy: Never
