apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: kargo-demo
spec:
  promotionPolicies:
  - stage: test
    autoPromotionEnabled: true
  - stage: uat
    autoPromotionEnabled: true
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: kargo-demo
  namespace: kargo-demo
spec:
  subscriptions:
  - git:
      repoURL: https://github.com/<username>/kargo-demo-gitops.git
      # Watch this branch instead of main. This is the "trunk" for this example.
      branch: helm
  - image:
      repoURL: nginx # Watch for new versions of this image
      semverConstraint: ^1.24.0
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: test
  namespace: kargo-demo
spec:
  subscriptions:
    warehouse: kargo-demo
  promotionMechanisms:
    argoCDAppUpdates:
    - appName: kargo-demo-test
      sourceUpdates:
      - repoURL: https://github.com/<username>/kargo-demo-gitops.git
        helm:
          images:
          - image: nginx
            key: image.name
            value: ImageAndTag # Update Application to reference the new image version
        updateTargetRevision: true # Update Application to reference the new commit
  verification:
    analysisTemplates:
    - name: kargo-demo
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: uat
  namespace: kargo-demo
spec:
  subscriptions:
    upstreamStages:
    - name: test # Watch for new commits and images
  promotionMechanisms:
    argoCDAppUpdates:
    - appName: kargo-demo-uat
      sourceUpdates:
      - repoURL: https://github.com/<username>/kargo-demo-gitops.git
        helm:
          images:
          - image: nginx
            key: image.name
            value: ImageAndTag # Update Application to reference the new image version
        updateTargetRevision: true # Update Application to reference the new commit
  verification:
    analysisTemplates:
    - name: kargo-demo
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod
  namespace: kargo-demo
spec:
  subscriptions:
    upstreamStages:
    - name: uat # Watch for new commits and images
  promotionMechanisms:
    argoCDAppUpdates:
    - appName: kargo-demo-prod
      sourceUpdates:
      - repoURL: https://github.com/<username>/kargo-demo-gitops.git
        helm:
          images:
          - image: nginx
            key: image.name
            value: ImageAndTag # Update Application to reference the new image version
        updateTargetRevision: true # Update Application to reference the new commit
  verification:
    analysisTemplates:
    - name: kargo-demo
---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: kargo-demo
  namespace: kargo-demo
spec:
  metrics:
  - name: test
    provider:
      job:
        metadata:
        spec:
          backoffLimit: 1
          template:
            spec:
              containers:
              - name: test
                image: alpine:latest
                command:
                - sleep
                - "20"
              restartPolicy: Never
